name: ARC Demo
on:
  workflow_dispatch:
jobs:
  Use-ARC:
    runs-on: arc-runners
    steps:
      - run: echo "ðŸŽ‰ Running on ARC self-hosted runner!"
      - run: sleep 10
      - run: echo "Repo:${{ github.repository }}, Ref:${{ github.ref }}"
